/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#FBF9F4',
        'on-background': '#1B1C19',
        surface: '#FBF9F4',
        'on-surface': '#1B1C19',
        'on-surface-variant': '#58605F',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F5F3EE',
        'surface-container': '#EFEEE9',
        'surface-container-high': '#EAE8E3',
        'surface-container-highest': '#E4E2DD',
        'surface-dim': '#DBDAD5',
        'primary-container': '#151D1C',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#7D8684',
        'on-primary-fixed-variant': '#9CA3AF',
        'inverse-surface': '#1F2928',
        'tertiary-fixed-dim': '#FFB955',
        'tertiary-fixed': '#FFDDB4',
        'tertiary-container': '#291800',
        'on-tertiary-container': '#B57700',
        'outline': '#737877',
        'outline-variant': '#E0DED7',
        'outline-light': '#EAE8E3',
        'error': '#BA1A1A',
        'error-container': '#FFDAD6',
        'on-error-container': '#93000A',
        'warning': '#D97706',
        'warning-container': '#FEF3C7',
        'on-warning-container': '#92400E',
        'success': '#15803D',
        'success-container': '#DCFCE7',
        'on-success-container': '#166534',
        'brand-gold': '#F59E0B',
        'brand-dark': '#111827',
      },
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"DM Mono"', 'monospace'],
        display: ['"DM Sans"', 'sans-serif'],
      },
      spacing: {
        'edge-margin': '24px',
        'container-max': '1440px',
        'section-gap': '32px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.375rem',
        xl: '0.5rem',
      },
      boxShadow: {
        subtle: '0 1px 2px rgba(0, 0, 0, 0.04)',
        card: '0 1px 3px rgba(0, 0, 0, 0.05), 0 1px 2px rgba(0, 0, 0, 0.03)',
      }
    },
  },
  plugins: [],
}
