-- DuesOS database schema
-- Run this in the Supabase SQL editor (or via psql) BEFORE running seed.sql.
-- Uses PostgreSQL's built-in gen_random_uuid(), available via the
-- pgcrypto extension, which is enabled by default on Supabase projects.

create extension if not exists pgcrypto;

-- =========================================================
-- businesses
-- One row per MSME using DuesOS. There's no login system yet,
-- so the backend currently treats the oldest row here as
-- "the" business.
-- =========================================================
create table if not exists businesses (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  industry text,
  email text,
  phone text,
  current_cash numeric(14, 2) not null default 0,
  minimum_cash_threshold numeric(14, 2) not null default 0,
  created_at timestamptz not null default now()
);

-- =========================================================
-- customers
-- The businesses' customers who owe them money.
-- payment_reliability is a 0-100 score (100 = always pays on time).
-- =========================================================
create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  average_payment_days numeric(6, 2) not null default 14,
  payment_reliability integer not null default 70
    check (payment_reliability between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists idx_customers_business_id on customers(business_id);

-- =========================================================
-- invoices
-- status is kept in sync by the backend whenever a payment is recorded.
-- =========================================================
create table if not exists invoices (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  customer_id uuid not null references customers(id) on delete cascade,
  invoice_number text,
  amount numeric(14, 2) not null check (amount > 0),
  issue_date date not null,
  due_date date not null,
  paid_date date,
  status text not null default 'pending'
    check (status in ('pending', 'due_soon', 'overdue', 'partially_paid', 'paid', 'disputed')),
  created_at timestamptz not null default now()
);

create index if not exists idx_invoices_business_id on invoices(business_id);
create index if not exists idx_invoices_customer_id on invoices(customer_id);
create index if not exists idx_invoices_status on invoices(status);

-- =========================================================
-- payments
-- An invoice can have multiple payments (e.g. partial payments over time).
-- =========================================================
create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references invoices(id) on delete cascade,
  amount numeric(14, 2) not null check (amount > 0),
  payment_date date not null,
  payment_method text,
  reference text,
  created_at timestamptz not null default now()
);

create index if not exists idx_payments_invoice_id on payments(invoice_id);

-- =========================================================
-- expenses
-- Used by the cash-flow forecast alongside expected invoice collections.
-- =========================================================
create table if not exists expenses (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  category text not null,
  description text,
  amount numeric(14, 2) not null check (amount > 0),
  due_date date not null,
  recurring boolean not null default false,
  status text not null default 'pending'
    check (status in ('pending', 'paid')),
  created_at timestamptz not null default now()
);

create index if not exists idx_expenses_business_id on expenses(business_id);

-- =========================================================
-- actions
-- A log of recommended/actioned follow-ups, generated by the
-- recommendation engine (or created manually later).
-- =========================================================
create table if not exists actions (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  invoice_id uuid references invoices(id) on delete set null,
  type text not null
    check (type in ('payment_reminder', 'request_payment_date', 'escalate', 'negotiate', 'financing', 'review')),
  priority text
    check (priority in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  description text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists idx_actions_business_id on actions(business_id);
create index if not exists idx_actions_invoice_id on actions(invoice_id);
